@host=9e9ab65etrial-dev-auth-transport-srv.cfapps.eu10.hana.ondemand.com


###
POST https://{{host}}/auth-transport/Suffix
Content-Type: application/json

{
  "destination":"AuthorizationAPI_Source", 
  "suffix": "!t113913"
}

###
POST https://{{host}}:{{port}}/auth-transport/Suffix
Content-Type: application/json

{
  "destination":"AuthorizationAPI_Target", 
  "suffix": "!t64770"
}

###
POST https://{{host}}/auth-transport/transportRoleCollections
Content-Type: application/json

{
    "destinations": {
        "source": "AuthorizationAPI_Source",
        "target": "AuthorizationAPI_Target"
    },
    "roleCollections": ["myxsuaa_Admin", "myxsuaa_Viewer"]
}